# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          與天通理
paginate:       5
baseurl:        "/sotongman.github.io"
url:            "https://sotongman.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         
  url:          
  email:        

# Custom vars
version:        3.4.1
github:
  repo:         https://sotongman.github.io

# Gems
gems:
  - jekyll-paginate
